FROM amazoncorretto:8 AS builder

WORKDIR /app
COPY ./backend-server/. .
RUN ./gradlew build -x test


FROM amazoncorretto:8

ARG SEMVER_FULL
ENV SEMVER_FULL=${SEMVER_FULL}

WORKDIR /app

COPY --from=builder /app/application/build/libs/*.jar /app/app.jar
EXPOSE 8081
CMD ["java", "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=localhost:5005", "-jar", "/app/app.jar"]
